### ISSUE TITLE
has table widget?

### ISSUE THREAD

**Issue by ddkwork** [razzie/riddle-solver#1]

**Comment by razzie** [comment]
Hey @ddkwork, if you mean the Setup page, then no. I have gio's flex layout there. Have a look at these, maybe you find something useful for your usecase:
https://pkg.go.dev/gioui.org/layout
https://pkg.go.dev/gioui.org/x/component

**Comment by ddkwork** [comment]
> Hey @ddkwork, if you mean the Setup page, then no. I have gio's flex layout there. Have a look at these, maybe you find something useful for your usecase:\nhttps://pkg.go.dev/gioui.org/layout\nhttps://pkg.go.dev/gioui.org/x/component

No, my means is this table, like charles

![OIP-C.jpeg](https://user-images.githubusercontent.com/19886504/193392974-401a9901-0c0d-4f93-b848-d32b3aa638b8.jpeg)

**Comment by ddkwork** [comment]
https://www.charlesproxy.com/

This table has dynamic add row， copy row and col with pop menu feature.

**Comment by razzie** [comment]
It would be nice to have similar functionality in Gio UI, but haven't come across any libraries that implement this. Also one thing to note is that Gio UI (the gui library used by my project) doesn't use native OS controls/widgets, but renders everything on its own.

**Comment by ddkwork** [comment]
> It would be nice to have similar functionality in Gio UI, but haven't come across any libraries that implement this. Also one thing to note is that Gio UI (the gui library used by my project) doesn't use native OS controls/widgets, but renders everything on its own.

So need you make one, because it is diffcute to me

**Comment by razzie** [comment]
Thanks for the interest, but I have no plans of implementing such things in the near future
